export const siteMeta = {
    brandName: "Nexus Fashion",
    shortName: "Nexus",
    brandTagline: "AI fashion for India's next style generation",
    supportEmail: "hello@nexusfashion.in",
    supportWhatsApp: "+91 98765 43210",
    headquarters: "Bengaluru, India"
};

export const collections = [
    { id: "new-gen", title: "New Gen Edit", description: "Trend-forward silhouettes for India's next style generation." },
    { id: "street", title: "Streetwear Grid", description: "Oversized hoodies, cargos, denim, and sharp footwear." },
    { id: "urban", title: "Urban Essentials", description: "Minimal accessories and polished daily-carry products." },
    { id: "workwear", title: "Workwear", description: "Office-ready pieces with a clean, elevated mood." },
    { id: "athleisure", title: "Athleisure", description: "Training-ready joggers, sneakers, and everyday active layers." }
];

export const catalogData = [
    { id: 1, slug: "cloud-oversized-hoodie", name: "Cloud Oversized Hoodie", image: "resources/product-1.jpg", audience: "unisex", category: "tops", collection: "street", price: 2499, compareAt: 3199, rating: 4.8, reviews: 148, badge: "Best Seller", colors: ["Ash Grey", "Mocha"], sizes: ["XS", "S", "M", "L", "XL"], fit: "Relaxed", fabric: "Premium brushed cotton fleece", delivery: "Free express delivery in metro cities", shortDescription: "Soft oversized hoodie for airport fits, creator looks, and clean streetwear styling.", tryOnZone: "top", featured: true },
    { id: 2, slug: "vintage-denim-jacket", name: "Vintage Denim Jacket", image: "resources/product-2.jpg", audience: "unisex", category: "outerwear", collection: "street", price: 3299, compareAt: 4099, rating: 4.7, reviews: 121, badge: "New Drop", colors: ["Classic Blue"], sizes: ["S", "M", "L", "XL", "XXL"], fit: "Regular", fabric: "Structured denim twill", delivery: "2 to 4 day delivery across India", shortDescription: "A distressed denim jacket with a clean vintage wash and all-season styling value.", tryOnZone: "outerwear", featured: true },
    { id: 3, slug: "utility-cargo-trousers", name: "Utility Cargo Trousers", image: "resources/product-3.jpg", audience: "men", category: "bottoms", collection: "street", price: 2199, compareAt: 2799, rating: 4.6, reviews: 94, badge: "Street Core", colors: ["Jet Black"], sizes: ["30", "32", "34", "36", "38"], fit: "Tapered cargo", fabric: "Structured nylon-cotton blend", delivery: "Cash on delivery available", shortDescription: "Clean black cargo trousers with stacked pocket detailing and a sharp street silhouette.", tryOnZone: "bottom", featured: false },
    { id: 4, slug: "core-white-sneakers", name: "Core White Sneakers", image: "resources/product-4.jpg", audience: "unisex", category: "footwear", collection: "urban", price: 2899, compareAt: 3599, rating: 4.9, reviews: 214, badge: "Most Loved", colors: ["Pure White"], sizes: ["5", "6", "7", "8", "9", "10", "11"], fit: "True to size", fabric: "Smooth vegan leather upper", delivery: "Free shipping and easy exchange", shortDescription: "Minimal white sneakers that work with denim, cargos, co-ords, and office casual looks.", tryOnZone: "footwear", featured: true },
    { id: 5, slug: "tech-utility-sling", name: "Tech Utility Sling", image: "resources/product-5.jpg", audience: "unisex", category: "accessories", collection: "urban", price: 1999, compareAt: 2499, rating: 4.5, reviews: 73, badge: "Daily Carry", colors: ["Matte Black"], sizes: ["One Size"], fit: "Adjustable strap", fabric: "Water-resistant utility shell", delivery: "Ships within 24 hours", shortDescription: "A smart utility sling for tech essentials, daily commute, and compact travel.", tryOnZone: "accessory-shoulder", featured: false },
    { id: 6, slug: "artist-graphic-tee-pack", name: "Artist Graphic Tee Pack", image: "resources/product-6.jpg", audience: "unisex", category: "tops", collection: "new-gen", price: 1699, compareAt: 2199, rating: 4.4, reviews: 65, badge: "Campus Pick", colors: ["White Multi"], sizes: ["S", "M", "L", "XL"], fit: "Boxy", fabric: "Combed cotton jersey", delivery: "Same week delivery pan-India", shortDescription: "A graphic tee set with art-led prints made for campus, content days, and casual layering.", tryOnZone: "top", featured: true },
    { id: 7, slug: "olive-street-cargos", name: "Olive Street Cargos", image: "resources/product-7.jpg", audience: "women", category: "bottoms", collection: "new-gen", price: 2299, compareAt: 2899, rating: 4.7, reviews: 109, badge: "Women's Edit", colors: ["Olive"], sizes: ["26", "28", "30", "32", "34"], fit: "High-rise relaxed", fabric: "Stretch utility cotton", delivery: "Free prepaid shipping", shortDescription: "High-rise olive cargos built for sneakers, crop tops, and creator-led styling.", tryOnZone: "bottom", featured: true },
    { id: 8, slug: "studio-platform-boots", name: "Studio Platform Boots", image: "resources/product-8.jpg", audience: "women", category: "footwear", collection: "new-gen", price: 3199, compareAt: 3999, rating: 4.8, reviews: 118, badge: "Party Edit", colors: ["Black"], sizes: ["4", "5", "6", "7", "8"], fit: "True to size", fabric: "Matte vegan upper", delivery: "Free size exchange", shortDescription: "Chunky black platform boots for concert fits, partywear, and bold city styling.", tryOnZone: "footwear", featured: true },
    { id: 9, slug: "bloom-print-tee", name: "Bloom Print Tee", image: "resources/product-9.jpg", audience: "women", category: "tops", collection: "new-gen", price: 1499, compareAt: 1899, rating: 4.5, reviews: 86, badge: "Soft Graphic", colors: ["White"], sizes: ["XS", "S", "M", "L"], fit: "Regular", fabric: "Soft touch cotton", delivery: "2 to 5 day delivery nationwide", shortDescription: "A clean white graphic tee with floral color placement for everyday women's styling.", tryOnZone: "top", featured: false },
    { id: 10, slug: "tailored-blazer-set", name: "Tailored Blazer Set", image: "resources/product-10.jpg", audience: "men", category: "outerwear", collection: "workwear", price: 3699, compareAt: 4499, rating: 4.8, reviews: 101, badge: "Office Ready", colors: ["Charcoal"], sizes: ["S", "M", "L", "XL", "XXL"], fit: "Slim tailored", fabric: "Structured suiting blend", delivery: "Next-day dispatch in select cities", shortDescription: "A polished blazer-led workwear essential for office days, events, and clean formal styling.", tryOnZone: "outerwear", featured: true },
    { id: 11, slug: "teal-statement-belt", name: "Teal Statement Belt", image: "resources/product-11.jpg", audience: "unisex", category: "accessories", collection: "urban", price: 999, compareAt: 1299, rating: 4.3, reviews: 49, badge: "Accessory Drop", colors: ["Teal"], sizes: ["One Size"], fit: "Adjustable", fabric: "Textured faux leather", delivery: "Easy nationwide shipping", shortDescription: "A color-led belt that adds sharp contrast to neutral trousers, denim, and skirts.", tryOnZone: "waist", featured: false },
    { id: 12, slug: "flex-knit-joggers", name: "Flex Knit Joggers", image: "resources/product-12.jpg", audience: "men", category: "bottoms", collection: "athleisure", price: 1899, compareAt: 2399, rating: 4.7, reviews: 78, badge: "Travel Ready", colors: ["Heather Grey"], sizes: ["S", "M", "L", "XL"], fit: "Slim taper", fabric: "Stretch knit blend", delivery: "Easy 7-day exchange", shortDescription: "Grey joggers for airport wear, athleisure fits, and polished off-duty comfort.", tryOnZone: "bottom", featured: false },
    { id: 13, slug: "canvas-city-tote", name: "Canvas City Tote", image: "resources/product-13.jpg", audience: "women", category: "accessories", collection: "new-gen", price: 1499, compareAt: 1899, rating: 4.6, reviews: 97, badge: "Campus Favorite", colors: ["Ivory"], sizes: ["One Size"], fit: "Shoulder carry", fabric: "Heavy canvas", delivery: "Fast delivery in Tier 1 and Tier 2 cities", shortDescription: "A structured canvas tote for college, work, and city movement with a clean premium look.", tryOnZone: "accessory-shoulder", featured: true },
    { id: 14, slug: "soft-rib-knit-sweater", name: "Soft Rib Knit Sweater", image: "resources/product-14.jpg", audience: "women", category: "tops", collection: "new-gen", price: 2199, compareAt: 2799, rating: 4.7, reviews: 84, badge: "Winter Soft", colors: ["Lilac Taupe"], sizes: ["XS", "S", "M", "L"], fit: "Relaxed cropped", fabric: "Rib knit blend", delivery: "Ships across India", shortDescription: "A soft rib knit sweater with a clean silhouette for colder evenings and layered looks.", tryOnZone: "top", featured: false },
    { id: 15, slug: "tan-city-boots", name: "Tan City Boots", image: "resources/product-15.jpg", audience: "women", category: "footwear", collection: "new-gen", price: 2999, compareAt: 3799, rating: 4.6, reviews: 72, badge: "City Night", colors: ["Tan"], sizes: ["4", "5", "6", "7", "8"], fit: "True to size", fabric: "Smooth faux leather", delivery: "Free prepaid delivery", shortDescription: "A sleek tan ankle boot for dresses, denims, and transitional evening styling.", tryOnZone: "footwear", featured: false },
    { id: 16, slug: "minimal-leather-watch", name: "Minimal Leather Watch", image: "resources/product-16.jpg", audience: "unisex", category: "accessories", collection: "urban", price: 1799, compareAt: 2299, rating: 4.5, reviews: 66, badge: "Refined Accessory", colors: ["Silver", "Black Strap"], sizes: ["One Size"], fit: "Adjustable strap", fabric: "Metal case with leather strap", delivery: "Ships within 24 hours", shortDescription: "A clean wristwatch for office, dinner, and polished everyday styling.", tryOnZone: "wrist", featured: false },
    { id: 17, slug: "off-duty-street-hoodie", name: "Off-Duty Street Hoodie", image: "resources/product-17.jpg", audience: "women", category: "tops", collection: "street", price: 2399, compareAt: 2999, rating: 4.6, reviews: 91, badge: "Lookbook Pick", colors: ["Black"], sizes: ["XS", "S", "M", "L", "XL"], fit: "Relaxed", fabric: "Heavy cotton fleece", delivery: "2 to 4 day delivery in India", shortDescription: "A black off-duty hoodie styled with accessories for a complete Gen-Z street look.", tryOnZone: "top", featured: false },
    { id: 18, slug: "geo-silk-scarf", name: "Geo Silk Scarf", image: "resources/product-18.jpg", audience: "women", category: "accessories", collection: "new-gen", price: 1299, compareAt: 1699, rating: 4.4, reviews: 52, badge: "Accessorize", colors: ["Coral Print"], sizes: ["One Size"], fit: "Multi-style", fabric: "Soft satin silk blend", delivery: "Ships across India", shortDescription: "A geometric scarf for neck styling, hair styling, or bag-detail fashion moments.", tryOnZone: "accessory-neck", featured: false },
    { id: 19, slug: "metro-utility-backpack", name: "Metro Utility Backpack", image: "resources/product-19.jpg", audience: "unisex", category: "accessories", collection: "urban", price: 2299, compareAt: 2899, rating: 4.6, reviews: 88, badge: "Commute Essential", colors: ["Graphite", "Tan"], sizes: ["One Size"], fit: "Back carry", fabric: "Durable structured utility shell", delivery: "Free shipping on prepaid orders", shortDescription: "A commuter backpack with laptop storage, travel-friendly structure, and everyday city utility.", tryOnZone: "accessory-backpack", featured: true },
    { id: 20, slug: "essential-layer-tank-set", name: "Essential Layer Tank Set", image: "resources/product-20.jpg", audience: "women", category: "tops", collection: "new-gen", price: 1899, compareAt: 2399, rating: 4.7, reviews: 111, badge: "New Gen Favorite", colors: ["Ivory", "Black", "Denim Blue"], sizes: ["XS", "S", "M", "L"], fit: "Body-skimming", fabric: "Rib stretch cotton", delivery: "Priority dispatch in 24 hours", shortDescription: "A layered tank-top edit built for women who style basics with wide-leg pants, skirts, and denims.", tryOnZone: "top", featured: true },
    { id: 21, slug: "soft-rib-shell-top", name: "Soft Rib Shell Top", image: "resources/product-21.jpg", audience: "women", category: "tops", collection: "new-gen", price: 1599, compareAt: 2099, rating: 4.7, reviews: 64, badge: "Fresh Drop", colors: ["Cloud White"], sizes: ["XS", "S", "M", "L"], fit: "Easy straight fit", fabric: "Light ribbed cotton jersey", delivery: "Priority dispatch in metro cities", shortDescription: "A clean sleeveless shell top built for layering, office edits, and easy AI fit checks.", tryOnZone: "top", featured: true },
    { id: 22, slug: "linen-wide-leg-pants", name: "Linen Wide-Leg Pants", image: "resources/product-22.jpg", audience: "women", category: "bottoms", collection: "workwear", price: 2499, compareAt: 3099, rating: 4.6, reviews: 58, badge: "Desk to Dinner", colors: ["Sand Beige"], sizes: ["26", "28", "30", "32", "34"], fit: "High-rise wide leg", fabric: "Breathable linen blend", delivery: "Free prepaid delivery", shortDescription: "Airy wide-leg trousers with a polished drape for summer workwear and elevated everyday styling.", tryOnZone: "bottom", featured: true },
    { id: 23, slug: "satin-column-midi-skirt", name: "Satin Column Midi Skirt", image: "resources/product-23.jpg", audience: "women", category: "bottoms", collection: "new-gen", price: 2199, compareAt: 2799, rating: 4.6, reviews: 47, badge: "Evening Pick", colors: ["Ink Black"], sizes: ["26", "28", "30", "32"], fit: "Straight midi column", fabric: "Soft drape satin blend", delivery: "Ships across India", shortDescription: "A sleek midi skirt that works with fitted tanks, shirts, and occasion-ready evening layering.", tryOnZone: "bottom", featured: false },
    { id: 24, slug: "washed-denim-overshirt-set", name: "Washed Denim Overshirt Set", image: "resources/product-24.jpg", audience: "unisex", category: "outerwear", collection: "street", price: 3399, compareAt: 4199, rating: 4.8, reviews: 82, badge: "Layering Hero", colors: ["Light Wash"], sizes: ["S", "M", "L", "XL"], fit: "Relaxed overshirt", fabric: "Soft washed denim", delivery: "2 to 4 day delivery pan-India", shortDescription: "A relaxed denim overshirt look with a clean white base layer for easy off-duty styling and AI try-on testing.", tryOnZone: "outerwear", featured: true },
    { id: 25, slug: "performance-black-cap", name: "Performance Black Cap", image: "resources/product-25.jpg", audience: "men", category: "accessories", collection: "urban", price: 999, compareAt: 1299, rating: 4.5, reviews: 53, badge: "Sport Utility", colors: ["Stealth Black"], sizes: ["One Size"], fit: "Adjustable back strap", fabric: "Lightweight performance twill", delivery: "Ships within 24 hours", shortDescription: "A sharp black cap for commute looks, gym layering, and everyday streetwear styling.", tryOnZone: "accessory-head", featured: false },
    { id: 26, slug: "monochrome-runner-sneakers", name: "Monochrome Runner Sneakers", image: "resources/product-26.jpg", audience: "men", category: "footwear", collection: "athleisure", price: 2899, compareAt: 3499, rating: 4.7, reviews: 69, badge: "Move Daily", colors: ["Triple Black"], sizes: ["7", "8", "9", "10", "11"], fit: "Cushioned regular fit", fabric: "Mesh and layered synthetic upper", delivery: "Fast delivery with easy exchange", shortDescription: "Chunky black runners tuned for travel days, casual outfits, and a stronger sporty silhouette.", tryOnZone: "footwear", featured: true }
];
